[package]
# this can have either - or _.
name = "pointers-threads"
version = "0.1.0"
edition = "2024"
build = "build.rs" # Optional, as Cargo looks for build.rs by default anyways
authors = ["Manish Gondhkar"]
description = "A Rust library that dives into Pointers, Asyncs and threads"
license = "MIT"
repository = "https://github.com/Manish-N-G/pointers-threads"

# not added rust version here, so clippy does checks in msrv in clippy.toml

# not sure I need documentation for the moment
# documentation = "https:://docs.rs/project-name"
readme = "README.md"
keywords = ["rust", "threads", "pointers", "async", "futures", "concurrency", "multithreading",
            "tasks", "tokio", "parallelism"]
categories = ["asynchronous", "multithreading", "futures", "concurrency", "programming"]

# Not related to any dev dependencies, but mainly used for some
# tools, scripts, plugins and things of that nature, that has no
# direct impact on the lib
[package.metadata]
[package.metadata.tools]

[package.metadata.spellcheck]
config = ".config/spellcheck.toml"

# automatically added
# [[examples]]
# name = "pin_selfref.rs"


[lib]
name = "pointers_threads"
# Note, lib names cannot contain - and need to be _ instead
path = "src/lib.rs"

[dependencies]
paste = "=1.0.15"
# tokio = "1.52.3"  #works but didnt get all the features
tokio = { version = "=1.52.3", features = ["full"] }
tokio-macros = { version = "=0.2.6" }
rayon = "=1.12.0"

# using trpl as a simple wrapper create for tokio for testing in our lib
trpl = "=0.3.0"

#NOTE: env lives in $CARGO_HOME/config.toml and
# CARGO_HOME defaults to .cargo
# We have our env there

[features]
default = ["full"]
pointers = []
async = []
threads = []
# tokio = ["dep:tokio"]
full = ["pointers", "async", "threads"]


[build-dependencies] 
# file-exists-macro = "0.1.0"   


#NOTE: "=1.1.0" gives the exact version while "1.1.0" is interpreted as "^1.1.0"
# and it means it could be updated from >1.1.0 to <2.0.0

# [package.metadata.docs.rs]
# playground = { url = "https://play.rust-lang.org/" }   # This enables the Run button


