[package]
# this can have either - or _.
name = "pointers-threads"
version = "0.1.0"
edition = "2024"
build = "build.rs" # Optional, as Cargo looks for build.rs by default anyways
authors = ["Manish Gondhkar"]
description = "A Rust library that dives into Pointers, Asyncs and threads"
license = "MIT"
repository = "https://github.com/Manish-N-G/pointers-threads"

# not added rust version here, so clippy does checks in msrv in clippy.toml

# not sure I need documentation for the moment
# documentation = "https:://docs.rs/project-name"
readme = "README.md"
keywords = ["rust", "threads", "pointers", "async", "futures", "concurrency", "multithreading",
            "tasks", "tokio", "parallelism"]
categories = ["asynchronous", "multithreading", "futures", "concurrency", "programming"]

# Not related to any dev dependencies, but mainly used for some
# tools, scripts, plugins and things of that nature, that has no
# direct impact on the lib
[package.metadata]
[package.metadata.tools]

[package.metadata.spellcheck]
config = ".config/spellcheck.toml"

# automatically added
# [[examples]]
# name = "pin_selfref.rs"


[lib]
name = "pointers_threads"
# Note, lib names cannot contain - and need to be _ instead
path = "src/lib.rs"

[dependencies]
paste = "=1.0.15"
# tokio = "1.52.3"  #works but didnt get all the features
tokio = { version = "=1.52.3", features = ["full"] }
tokio-macros = { version = "=0.2.6" }
rayon = "=1.12.0"

# using trpl as a simple wrapper create for tokio for testing in our lib
trpl = "=0.3.0"

#NOTE: env lives in $CARGO_HOME/config.toml and
# CARGO_HOME defaults to .cargo
# We have our env there

[features]
default = ["full"]
pointers = []
async = []
threads = []
# tokio = ["dep:tokio"]
full = ["pointers", "async", "threads"]
nightly-bench = [] # Only for cargo nightly version
# can do something like cargo +nightly bench --feature nightly-bench
# notice we can also use nightly-bench or nightly_bench


[build-dependencies] 
# file-exists-macro = "0.1.0"   

[dev-dependencies]
# formatting giving me issues then it goes to new line
# have to be done carefully
criterion = { version = "=0.8.2", features = [
   "rayon", 

   # to get html display results and charts however, 
   # this might be active by default for this version
   # "html-reports",

   "plotters",
   "cargo_bench_support",
   "async_tokio"
] }

# for criterion bench
# harness is a wrapper/runner that automatically provides to run test or benchmarks.
[[bench]]
name = "crit_benches"
harness = false

# for normal bench
[[bench]]
name = "norm_benches"
harness = true


#NOTE: "=1.1.0" gives the exact version while "1.1.0" is interpreted as "^1.1.0"
# and it means it could be updated from >1.1.0 to <2.0.0

# [package.metadata.docs.rs]
# playground = { url = "https://play.rust-lang.org/" }   # This enables the Run button

# This can be used in clippy.toml. See clippy.toml to know more
[lints.clippy]
# pedantic = {level = "deny", priority = -1} # UM, ACTUALLY
# nursery = {level = "deny", priority = -1} # BETA LINTS
# # DENY PANIC
# unwrap_used = "deny"
# expect_used = "deny"
# indexing_slicing = "deny"
# arithmetic_side_effects = "deny"
# unreachable = "deny"
# unimplemented = "deny"
# unchecked_time_subtraction = "deny"
todo = "deny"
# string_slice = "deny"
# panic_in_result_fn = "deny"
# panic = "deny"
# exit = "deny"
# as_conversion = "deny"
